### ISSUE TITLE
Input should allow tiff/tiff/jpg

### ISSUE THREAD

**Issue by lwcvl** [among/fusus#1]
Scripts are too clean currently: tucking away too much of the mechanics behind the scenes which makes adapting it to different situations difficult. Most images we will process are tiff or tif, input for pages and elements should accommodate this.

**Comment by dirkroorda** [comment]
Tiff is already possible: pass parameter `ext='tiff'.

This is the general principle: most settings that the program uses can be overridden when calling a method.

There is now also a parameter `batch=False`. In batch mode the standard settings are chosen, and only transformations needed for the output are being done, there is no reporting of hits, and repetitive actions are taken out of the loop.

There should be more documentation, I will add that gradually to the docstrings, and expose them in html pages.

**Comment by dirkroorda** [comment]
In the meanwhile, the user does not have to specify extensions anymore.
