### ISSUE TITLE
Adaption to demargined

### ISSUE THREAD

**Issue by lwcvl** [among/fusus#2]
Demargined zou het grootste vlak moeten kiezen en alleen die overhouden, zodat valse strepen ook worden gemarginaliseerd. 

Met rode pijlen aangegeven wat weg mag.

<img width="1008" alt="Screen Shot 2020-04-02 at 13 54 25" src="https://user-images.githubusercontent.com/46796990/78246545-9e48e200-74e9-11ea-95c5-70941de3de29.png">

**Comment by dirkroorda** [comment]
Yes. Strange, I did not expect material to remain there!

**Comment by dirkroorda** [comment]
Here is the histogram:

![image](https://user-images.githubusercontent.com/1374704/78538345-1f0d2400-77f1-11ea-8df9-d18556ae9870.png)

I need to analyse the connected chunks and retain the one that is larger than half the page width.

**Comment by dirkroorda** [comment]
Done. Will be in next release.
